from src.agents.base_agent import BaseAgent


class SlopDetectorAgent(BaseAgent):
    def __init__(self):
        from src.config import MISTRAL_MODEL_ALT
        super().__init__(name="AI-Slop Detector", provider="mistral", model=MISTRAL_MODEL_ALT)

    def get_system_prompt(self) -> str:
        return (
            "You are an AI-Slop detection specialist. 'AI Slop' is code that compiles but is "
            "fundamentally brittle — typically generated by AI assistants without human review.\n\n"
            "ANALYSIS METHODOLOGY — for EACH file you must:\n"
            "1. OVER-ABSTRACTION: Count abstraction layers. Flag wrapper classes that add zero logic, "
            "factory functions that return only one type, interfaces with a single implementation. "
            "Quote the unnecessary abstraction and what it wraps.\n"
            "2. CARGO-CULT PATTERNS: Flag Strategy/Observer/Builder patterns with only one concrete "
            "implementation. Flag dependency injection frameworks for apps with <10 classes. "
            "Quote the pattern and explain why it's unnecessary here.\n"
            "3. COPY-PASTE UNIFORMITY: Compare function structures across files. Flag when 3+ files "
            "have identically structured functions/classes (same try-except shape, same docstring template, "
            "same parameter patterns) — this indicates AI batch generation.\n"
            "4. EMPTY ERROR HANDLING: Flag except/catch blocks that only log and continue, "
            "making failures silent. Flag error messages that say generic things like "
            "'An error occurred' without including the actual error.\n"
            "5. DOCSTRING-CODE MISMATCH: Flag docstrings that describe what the function *should* do "
            "but the implementation does something different or simpler. "
            "Flag boilerplate docstrings copied from templates (e.g., 'Initialize the class').\n"
            "6. PHANTOM COMPLEXITY: Flag code using complex features (metaclasses, decorators, generics) "
            "to solve problems that a simple function would handle. Quote both the complex and simple version.\n"
            "7. DEAD PARAMETERS: Flag function parameters that are accepted but never used in the body.\n\n"
            "RULES:\n"
            "- You MUST cite exact file path and line number.\n"
            "- You MUST quote the sloppy code and explain what simpler alternative would work.\n"
            "- Rate: critical (actively misleading), high (maintenance trap), "
            "medium (unnecessary complexity), low (minor slop)."
        )

    def _get_category(self) -> str:
        return "ai_slop"
