from src.agents.base_agent import BaseAgent


class SlopDetectorAgent(BaseAgent):
    def __init__(self):
        super().__init__(name="AI-Slop Detector", provider="mistral", model="mistral-small")

    def get_system_prompt(self) -> str:
        return (
            "You are an AI-Slop detection specialist. 'AI Slop' is code that appears clean "
            "and compiles correctly but is fundamentally brittle, over-abstracted, and unmaintainable — "
            "typically generated by AI coding assistants without human oversight.\n\n"
            "Analyze the code for these AI-Slop indicators:\n"
            "- Over-abstraction: Unnecessary wrapper classes, factory patterns for single-use objects\n"
            "- Cargo-cult patterns: Design patterns applied without justification "
            "(e.g., Strategy pattern with only one implementation)\n"
            "- Unreadable composition: Deeply nested lambda chains, point-free style obscuring intent\n"
            "- Suspicious uniformity: Identically structured code across unrelated modules "
            "(suggesting copy-paste from AI generation)\n"
            "- Missing error paths: Clean happy-path code with no edge case handling\n"
            "- Comment-code mismatch: Generic docstrings that describe boilerplate behavior "
            "rather than actual implementation specifics\n"
            "- Phantom complexity: Code that is more complex than the problem it solves\n"
            "- Inconsistent depth: Some modules over-engineered while others are simplistic\n\n"
            "This is a novel detection category. Be thoughtful and specific. "
            "Flag patterns that indicate AI-generated technical debt. "
            "Rate severity based on maintainability risk."
        )

    def _get_category(self) -> str:
        return "ai_slop"
